// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711025010_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Author = "William Blackstone",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6481),
                            CreatedById = "1",
                            ISBN = "9780198720527",
                            PublishedDate = new DateTime(1765, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Commentaries on the Laws of England"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Oliver Wendell Holmes Jr.",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6483),
                            CreatedById = "1",
                            ISBN = "9780486450060",
                            PublishedDate = new DateTime(1881, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Common Law"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Nicholas J. McBride",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6484),
                            CreatedById = "1",
                            ISBN = "9781292086907",
                            PublishedDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Letters to a Law Student"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Joshua Dressler",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6485),
                            CreatedById = "1",
                            ISBN = "9781531016185",
                            PublishedDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding Criminal Law"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Bryan A. Garner",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6486),
                            CreatedById = "1",
                            ISBN = "9780226283937",
                            PublishedDate = new DateTime(2013, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Legal Writing in Plain English"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Erwin Chemerinsky",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6487),
                            CreatedById = "1",
                            ISBN = "9781543813074",
                            PublishedDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Constitutional Law: Principles and Policies"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Benjamin N. Cardozo",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6488),
                            CreatedById = "1",
                            ISBN = "9780486443864",
                            PublishedDate = new DateTime(1921, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Nature of the Judicial Process"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Jay M. Feinman",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6489),
                            CreatedById = "1",
                            ISBN = "9780199341691",
                            PublishedDate = new DateTime(2014, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Law 101: Everything You Need to Know About American Law"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Ewan McKendrick",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6490),
                            CreatedById = "1",
                            ISBN = "9780198855298",
                            PublishedDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Contract Law: Text, Cases, and Materials"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Tom Bingham",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6491),
                            CreatedById = "1",
                            ISBN = "9780141034539",
                            PublishedDate = new DateTime(2011, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Rule of Law"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Harper Lee",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6492),
                            CreatedById = "1",
                            ISBN = "9780061120084",
                            PublishedDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 14,
                            Author = "John Rawls",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6504),
                            CreatedById = "1",
                            ISBN = "9780674000780",
                            PublishedDate = new DateTime(1971, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Theory of Justice"
                        },
                        new
                        {
                            Id = 15,
                            Author = "H.L.A. Hart",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6505),
                            CreatedById = "1",
                            ISBN = "9780199644709",
                            PublishedDate = new DateTime(1961, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Concept of Law"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Deborah L. Rhode",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6506),
                            CreatedById = "1",
                            ISBN = "9780195328719",
                            PublishedDate = new DateTime(2007, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ethics in the Practice of Law"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Antonin Scalia & Bryan A. Garner",
                            CreatedAt = new DateTime(2025, 7, 11, 2, 50, 10, 351, DateTimeKind.Utc).AddTicks(6507),
                            CreatedById = "1",
                            ISBN = "9780314184719",
                            PublishedDate = new DateTime(2008, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Making Your Case: The Art of Persuading Judges"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "testuser@example.com",
                            FirstName = "TestUser",
                            LastName = "Test",
                            PasswordHash = "$2a$11$Xlf01hU5eeVdXz0AqVZLFeJ06ZBjGD4GOzrwf7alCweHRhJj1r04m",
                            TokenVersion = "2a3bc995-658a-477f-b08e-372cf9718962",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
